<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import PublicLayout from '../components/PublicLayout.vue'
import EmailGate from '../components/EmailGate.vue'
import { commentsApi, postsApi } from '../api'
import { useFavoritesStore } from '../stores/favorites'
import { useVisitorStore } from '../stores/visitor'
import { buildTableOfContents, type TocItem } from '../utils/article-reading'
import type { Comment, PostDetail, PostNavigation } from '@shared/types'

const route = useRoute(); const visitor = useVisitorStore(); const favorites = useFavoritesStore()
const post = ref<PostDetail | null>(null); const comments = ref<Comment[]>([]); const navigation = ref<PostNavigation>({ previous: null, next: null }); const toc = ref<TocItem[]>([]); const articleRef = ref<HTMLElement | null>(null)
const state = ref<'loading' | 'ready' | 'error'>('loading'); const error = ref(''); const commentState = ref<'loading' | 'ready' | 'error'>('loading'); const commentMessage = ref(''); const content = ref(''); const progress = ref(0); let viewTimer: number | undefined
const postId = computed(() => post.value?.id || 0)
function updateProgress() { const element = articleRef.value; if (!element) return; const height = element.offsetHeight - window.innerHeight; progress.value = height <= 0 ? 100 : Math.max(0, Math.min(100, Math.round((-element.getBoundingClientRect().top / height) * 100))) }
async function loadComments() { if (!postId.value) return; commentState.value = 'loading'; try { comments.value = (await commentsApi.listComments(postId.value, { page: 1, limit: 20 })).data; commentState.value = 'ready' } catch { comments.value = []; commentState.value = 'error' } }
async function loadPost() { state.value = 'loading'; error.value = ''; try { post.value = await postsApi.getPostDetail(String(route.params.id)); navigation.value = await postsApi.getNavigation(post.value.id); state.value = 'ready'; await nextTick(); if (articleRef.value) toc.value = buildTableOfContents(articleRef.value); void loadComments(); viewTimer = window.setTimeout(() => { if (postId.value) void postsApi.recordPostView(postId.value) }, 10000) } catch (reason) { post.value = null; state.value = 'error'; error.value = reason instanceof Error ? reason.message : '文章不存在或暂未发布。'; commentState.value = 'ready' } }
async function submitComment() { if (!visitor.hasProfile || !postId.value || !content.value.trim()) return; try { const result = await commentsApi.createComment(postId.value, { nickname: visitor.nickname, email: visitor.email, content: content.value.trim() }); content.value = ''; commentMessage.value = result.is_approved ? '评论已发布。' : '已提交，等待审核。'; await loadComments() } catch { commentMessage.value = '评论提交失败，请稍后再试。' } }
async function copyLink() { try { await navigator.clipboard.writeText(window.location.href); error.value = '链接已复制。' } catch { error.value = '复制链接失败，请手动复制地址栏。' } }
onMounted(() => { window.addEventListener('scroll', updateProgress, { passive: true }); void loadPost() }); onBeforeUnmount(() => { window.clearTimeout(viewTimer); window.removeEventListener('scroll', updateProgress) })
</script>

<template><PublicLayout><template #title>{{ post?.title || '文章' }}</template><template #subtitle><span v-if="post">{{ post.created_at }} · 阅读 {{ post.views }} · {{ post.tags.join(' / ') }}</span></template><div class="reading-progress" :style="{ width: `${progress}%` }" /><p v-if="state === 'loading'" class="content-state">正在加载文章…</p><div v-else-if="state === 'error'" class="content-state"><p>{{ error }}</p><RouterLink class="btn" to="/posts">返回文章列表</RouterLink></div><template v-else-if="post"><div class="reader-actions"><button class="btn" @click="copyLink">复制链接</button><button class="btn" :aria-pressed="favorites.has(post.id)" @click="favorites.toggle(post.id)">{{ favorites.has(post.id) ? '已收藏' : '收藏' }}</button></div><img v-if="post.cover_url" class="post-cover" :src="post.cover_url" alt="" /><aside v-if="toc.length" class="toc"><strong>目录</strong><a v-for="item in toc" :key="item.id" :class="`toc-level-${item.level}`" :href="`#${item.id}`">{{ item.text }}</a></aside><article ref="articleRef" class="panel article-content" v-html="post.content_html" /><nav v-if="navigation.previous || navigation.next" class="pagination"><RouterLink v-if="navigation.previous" class="btn" :to="`/posts/${navigation.previous.id}`">上一篇：{{ navigation.previous.title }}</RouterLink><RouterLink v-if="navigation.next" class="btn" :to="`/posts/${navigation.next.id}`">下一篇：{{ navigation.next.title }}</RouterLink></nav><section class="panel comment-panel"><h2>评论</h2><p v-if="commentState === 'loading'" class="content-state">正在加载评论…</p><p v-else-if="commentState === 'error'" class="content-state">评论加载失败，请稍后重试。</p><p v-else-if="!comments.length" class="content-state">暂无评论</p><div v-else class="comment-list"><article v-for="item in comments" :key="item.id" class="message-card"><strong>{{ item.nickname }}</strong><p>{{ item.content }}</p><time>{{ item.created_at }}</time></article></div><p v-if="commentMessage" class="notice">{{ commentMessage }}</p><EmailGate scene="评论" /><form v-if="visitor.hasProfile" class="composer" @submit.prevent="submitComment"><textarea v-model="content" required maxlength="800" placeholder="认真读完后的想法，可以从这里开始。" /><button class="btn primary">提交评论</button></form></section></template></PublicLayout></template>
